### ISSUE TITLE
use more complex examples

### ISSUE THREAD

**Issue by baboon-king** [liyupi/sql-generator#1]
> yupi：你能体会手写 1500 行 SQL、牵一发而动全身的恐惧么？

建议使用 1500 行 SQL 做为默认示例 🙈

手动狗头🐶

**Comment by liyupi** [comment]
谢谢，今天又搞出一个 3000 行的，数据库都存不下了

**Comment by baboon-king** [comment]
> 谢谢，今天又搞出一个 3000 行的，数据库都存不下了

啥业务，这么大！

**Comment by liyupi** [comment]
已提供
