### ISSUE TITLE
支持什么数据库？生成sql性能如何？

### ISSUE THREAD

**Issue by kiwimg** [liyupi/sql-generator#10]
支持什么数据库？生成sql性能如何？

**Comment by jerry4718** [comment]
> 

大体过了一遍逻辑，和我看到效果时设想的实现基本上是一致的，简单小巧，但是超级有用，核心就是很单纯的在处理字符串，
至于支持什么数据库，只要符合逻辑，所有数据库的sql应该都能生成，甚至写sql以外的东西都可以，比如小说(只要符号不冲突)，
然后说性能，如果问的是生成出来的sql在数据库里面的执行性能，那应该不在范围内，sql逻辑还是需要人为控制的，毕竟作者意图并不在sql优化

(原来是鱼皮啊？那没事了)

**Comment by PengLuan** [comment]
对于这种需求 一条 sql 搞定合理么？

**Comment by liyupi** [comment]
不能更合理




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "liyupi/sql-generator"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年6月12日(星期天) 下午3:53
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;Re: [liyupi/sql-generator] 支持什么数据库？生成sql性能如何？ (Issue #10)





 
对于这种需求 一条 sql 搞定合理么？
