### ISSUE TITLE
建议编辑器使用yaml格式，可读性好，编写方便

### ISSUE THREAD

**Issue by xwxgjs** [liyupi/sql-generator#2]
![图片](https://user-images.githubusercontent.com/77133362/168117628-19450758-bde6-493c-8aed-a57ab573f451.png)
将上面的json转换成yaml之后，可读性明显提升。是否考虑搞一下？

**Comment by liyupi** [comment]
我做这个工具的初衷是为了解决我自己的诉求，所以使用了通用性更强、使用更广泛的 json，当然支持 yaml 也是完全没问题的！这个工具逻辑很简单，欢迎贡献代码哦~
