### ISSUE TITLE
鱼皮你好，复杂示例中的表格所对应的数据库表DDL可以提供一下吗？谢谢！

### ISSUE THREAD

**Issue by HHawking** [liyupi/sql-generator#7]
鱼皮你好，复杂示例中的表格所对应的数据库表DDL可以提供一下吗？谢谢！

**Comment by liyupi** [comment]
是指视频中提到的么？抱歉，这个没办法提供哈，我们都是数仓里的大表，其实了解项目中体现的思维方式就可以了。
