### ISSUE TITLE
增加生成的sql语法校验是否可行

### ISSUE THREAD

**Issue by moshengrenzenme** [liyupi/sql-generator#9]
这个工具对我帮助很大，但是我在使用的是否发现生成的sql没有语法校验，我自己也查了几个可以校验的工具像是sql-parse，有部分的语法不正确，提示好像不够友好，sql-compile我用node不能运行，不知道大佬有没有什么好的包，所以上来和大佬讨论一下（b站粉丝，下次一定）

**Comment by liyupi** [comment]
感谢，之所以没加语法校验，一方面是因为我自己暂时没有这个需求，如果要校验 SQL 直接复制语句执行一下就好了，原则上在该工具中只维护 JSON、不修改 SQL。另一方面是因为不同数据引擎对 SQL 的语法校验规则有细微的差别，不方便进行统一。当然，用通用的 sql 解析做基础校验是 ok 的，有的话可能也更好一些。可以搜下：sqllint（我没用过，听说过）

**Comment by moshengrenzenme** [comment]
> 感谢，之所以没加语法校验，一方面是因为我自己暂时没有这个需求，如果要校验 SQL 直接复制语句执行一下就好了，原则上在该工具中只维护 JSON、不修改 SQL。另一方面是因为不同数据引擎对 SQL 的语法校验规则有细微的差别，不方便进行统一。当然，用通用的 sql 解析做基础校验是 ok 的，有的话可能也更好一些。可以搜下：sqllint（我没用过，听说过）

感谢大佬评论，我也是发了以后才想到只能校验通用sql，毕竟方言太多了

**Comment by 20154172011** [comment]
大佬，对于没有学过前端的人，想学习一下这个生成器，学习的路线应该是怎么样的呢？造轮子非常好奇
